In [4]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np
from faker import Faker
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold, KFold, cross_val_predict, GridSearchCV
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn import linear_model
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score
from sklearn.datasets import load_digits
from adspy_shared_utilities import plot_feature_importances
import matplotlib.pyplot as plt
fake = Faker()
digits = load_digits

In [30]:
df = pd.read_csv('D:/talent.csv', sep=';')

In [31]:
df.head()

id    prenom          nom genre  age background    cohorte  tauxPart  \
0  3711   Michael     Robinson     F   18   Master 1  cohorte 5        29   
1  7613      Kyle       Miller     M   18  Licence 3  cohorte 7        24   
2  4420  Jennifer  Christensen     M   18   Master 1  cohorte 7        14   
3  4940      John        Smith     M   24  Licence 3  cohorte 5        24   
4  5320     Diana       Hunter     M   18  Licence 3  cohorte 6        38   

   visiPlat  discussion  noteTalent  noteInst    retards   absences  parti  
0        16          20          19         2  Dessous-7   Dessus-3      1  
1        20          25          18        13  Dessous-7   Dessus-3      0  
2         7          30          16         1   Dessus-7   Dessus-3      1  
3        25          35          17         7   Dessus-7   Dessus-3      0  
4        50          50           6         5   Dessus-7  Dessous-3      0

In [32]:
df.corr(method='spearman').style.format("{:.2}").background_gradient(cmap=plt.get_cmap('coolwarm'))

In [33]:
genre= pd.get_dummies(df["genre"])
genre.head()

F  M
0  1  0
1  0  1
2  0  1
3  0  1
4  0  1

In [34]:
df = pd.concat([df, genre], axis=1)
df[['genre', 'F', 'M']].head()

genre  F  M
0     F  1  0
1     M  0  1
2     M  0  1
3     M  0  1
4     M  0  1

In [35]:
df.head()

id    prenom          nom genre  age background    cohorte  tauxPart  \
0  3711   Michael     Robinson     F   18   Master 1  cohorte 5        29   
1  7613      Kyle       Miller     M   18  Licence 3  cohorte 7        24   
2  4420  Jennifer  Christensen     M   18   Master 1  cohorte 7        14   
3  4940      John        Smith     M   24  Licence 3  cohorte 5        24   
4  5320     Diana       Hunter     M   18  Licence 3  cohorte 6        38   

   visiPlat  discussion  noteTalent  noteInst    retards   absences  parti  F  \
0        16          20          19         2  Dessous-7   Dessus-3      1  1   
1        20          25          18        13  Dessous-7   Dessus-3      0  0   
2         7          30          16         1   Dessus-7   Dessus-3      1  0   
3        25          35          17         7   Dessus-7   Dessus-3      0  0   
4        50          50           6         5   Dessus-7  Dessous-3      0  0   

   M  
0  0  
1  1  
2  1  
3  1  
4  1

In [36]:
background= pd.get_dummies(df["background"])
background.head()

Licence 3  Master 1  Master 2
0          0         1         0
1          1         0         0
2          0         1         0
3          1         0         0
4          1         0         0

In [37]:
df = pd.concat([df, background], axis=1)
df[['background', 'Licence 3', 'Master 1', 'Master 2']].head()

background  Licence 3  Master 1  Master 2
0   Master 1          0         1         0
1  Licence 3          1         0         0
2   Master 1          0         1         0
3  Licence 3          1         0         0
4  Licence 3          1         0         0

In [38]:
df.head()

id    prenom          nom genre  age background    cohorte  tauxPart  \
0  3711   Michael     Robinson     F   18   Master 1  cohorte 5        29   
1  7613      Kyle       Miller     M   18  Licence 3  cohorte 7        24   
2  4420  Jennifer  Christensen     M   18   Master 1  cohorte 7        14   
3  4940      John        Smith     M   24  Licence 3  cohorte 5        24   
4  5320     Diana       Hunter     M   18  Licence 3  cohorte 6        38   

   visiPlat  discussion  noteTalent  noteInst    retards   absences  parti  F  \
0        16          20          19         2  Dessous-7   Dessus-3      1  1   
1        20          25          18        13  Dessous-7   Dessus-3      0  0   
2         7          30          16         1   Dessus-7   Dessus-3      1  0   
3        25          35          17         7   Dessus-7   Dessus-3      0  0   
4        50          50           6         5   Dessus-7  Dessous-3      0  0   

   M  Licence 3  Master 1  Master 2  
0  0          0         1         0  
1  1          1         0         0  
2  1          0         1         0  
3  1          1         0         0  
4  1          1         0         0

In [39]:
cohorte= pd.get_dummies(df["cohorte"])
cohorte.head()

cohorte 5  cohorte 6  cohorte 7
0          1          0          0
1          0          0          1
2          0          0          1
3          1          0          0
4          0          1          0

In [40]:
df = pd.concat([df, cohorte], axis=1)
df[['cohorte', 'cohorte 5', 'cohorte 6', 'cohorte 7']].head()

cohorte  cohorte 5  cohorte 6  cohorte 7
0  cohorte 5          1          0          0
1  cohorte 7          0          0          1
2  cohorte 7          0          0          1
3  cohorte 5          1          0          0
4  cohorte 6          0          1          0

In [41]:
df.head()

id    prenom          nom genre  age background    cohorte  tauxPart  \
0  3711   Michael     Robinson     F   18   Master 1  cohorte 5        29   
1  7613      Kyle       Miller     M   18  Licence 3  cohorte 7        24   
2  4420  Jennifer  Christensen     M   18   Master 1  cohorte 7        14   
3  4940      John        Smith     M   24  Licence 3  cohorte 5        24   
4  5320     Diana       Hunter     M   18  Licence 3  cohorte 6        38   

   visiPlat  discussion  ...   absences  parti  F  M  Licence 3  Master 1  \
0        16          20  ...   Dessus-3      1  1  0          0         1   
1        20          25  ...   Dessus-3      0  0  1          1         0   
2         7          30  ...   Dessus-3      1  0  1          0         1   
3        25          35  ...   Dessus-3      0  0  1          1         0   
4        50          50  ...  Dessous-3      0  0  1          1         0   

   Master 2  cohorte 5  cohorte 6  cohorte 7  
0         0          1          0          0  
1         0          0          0          1  
2         0          0          0          1  
3         0          1          0          0  
4         0          0          1          0  

[5 rows x 23 columns]

In [42]:
retards= pd.get_dummies(df["retards"])
retards.head()

Dessous-7  Dessus-7
0          1         0
1          1         0
2          0         1
3          0         1
4          0         1

In [43]:
df = pd.concat([df, retards], axis=1)
df[['retards', 'Dessous-7', 'Dessus-7']].head()

retards  Dessous-7  Dessus-7
0  Dessous-7          1         0
1  Dessous-7          1         0
2   Dessus-7          0         1
3   Dessus-7          0         1
4   Dessus-7          0         1

In [44]:
df.head()

id    prenom          nom genre  age background    cohorte  tauxPart  \
0  3711   Michael     Robinson     F   18   Master 1  cohorte 5        29   
1  7613      Kyle       Miller     M   18  Licence 3  cohorte 7        24   
2  4420  Jennifer  Christensen     M   18   Master 1  cohorte 7        14   
3  4940      John        Smith     M   24  Licence 3  cohorte 5        24   
4  5320     Diana       Hunter     M   18  Licence 3  cohorte 6        38   

   visiPlat  discussion  ...  F  M Licence 3 Master 1  Master 2  cohorte 5  \
0        16          20  ...  1  0         0        1         0          1   
1        20          25  ...  0  1         1        0         0          0   
2         7          30  ...  0  1         0        1         0          0   
3        25          35  ...  0  1         1        0         0          1   
4        50          50  ...  0  1         1        0         0          0   

   cohorte 6  cohorte 7  Dessous-7  Dessus-7  
0          0          0          1         0  
1          0          1          1         0  
2          0          1          0         1  
3          0          0          0         1  
4          1          0          0         1  

[5 rows x 25 columns]

In [45]:
absences= pd.get_dummies(df["absences"])
absences.head()

Dessous-3  Dessus-3
0          0         1
1          0         1
2          0         1
3          0         1
4          1         0

In [46]:
df = pd.concat([df, absences], axis=1)
df[['absences', 'Dessous-3', 'Dessus-3']].head()

absences  Dessous-3  Dessus-3
0   Dessus-3          0         1
1   Dessus-3          0         1
2   Dessus-3          0         1
3   Dessus-3          0         1
4  Dessous-3          1         0

In [47]:
df.head()

id    prenom          nom genre  age background    cohorte  tauxPart  \
0  3711   Michael     Robinson     F   18   Master 1  cohorte 5        29   
1  7613      Kyle       Miller     M   18  Licence 3  cohorte 7        24   
2  4420  Jennifer  Christensen     M   18   Master 1  cohorte 7        14   
3  4940      John        Smith     M   24  Licence 3  cohorte 5        24   
4  5320     Diana       Hunter     M   18  Licence 3  cohorte 6        38   

   visiPlat  discussion  ...  Licence 3  Master 1 Master 2 cohorte 5  \
0        16          20  ...          0         1        0         1   
1        20          25  ...          1         0        0         0   
2         7          30  ...          0         1        0         0   
3        25          35  ...          1         0        0         1   
4        50          50  ...          1         0        0         0   

   cohorte 6  cohorte 7  Dessous-7  Dessus-7  Dessous-3  Dessus-3  
0          0          0          1         0          0         1  
1          0          1          1         0          0         1  
2          0          1          0         1          0         1  
3          0          0          0         1          0         1  
4          1          0          0         1          1         0  

[5 rows x 27 columns]

In [48]:
id = df["id"]
prenom = df["prenom"]
nom = df["nom"]
genre = df["genre"]
background = df["background"]
cohorte = df["cohorte"]
retards = df["retards"]
absences = df["absences"]

In [49]:

del df["prenom"]
del df["nom"]
del df["genre"]
del df["background"]
del df["cohorte"]
del df["retards"]
del df["absences"]

In [50]:
df.head()

id  age  tauxPart  visiPlat  discussion  noteTalent  noteInst  parti  F  \
0  3711   18        29        16          20          19         2      1  1   
1  7613   18        24        20          25          18        13      0  0   
2  4420   18        14         7          30          16         1      1  0   
3  4940   24        24        25          35          17         7      0  0   
4  5320   18        38        50          50           6         5      0  0   

   M  Licence 3  Master 1  Master 2  cohorte 5  cohorte 6  cohorte 7  \
0  0          0         1         0          1          0          0   
1  1          1         0         0          0          0          1   
2  1          0         1         0          0          0          1   
3  1          1         0         0          1          0          0   
4  1          1         0         0          0          1          0   

   Dessous-7  Dessus-7  Dessous-3  Dessus-3  
0          1         0          0         1  
1          1         0          0         1  
2          0         1          0         1  
3          0         1          0         1  
4          0         1          1         0

In [51]:
df = pd.concat([df, id], axis=1)

In [52]:
df.head()

id  age  tauxPart  visiPlat  discussion  noteTalent  noteInst  parti  F  \
0  3711   18        29        16          20          19         2      1  1   
1  7613   18        24        20          25          18        13      0  0   
2  4420   18        14         7          30          16         1      1  0   
3  4940   24        24        25          35          17         7      0  0   
4  5320   18        38        50          50           6         5      0  0   

   M  ...  Master 1  Master 2  cohorte 5  cohorte 6  cohorte 7  Dessous-7  \
0  0  ...         1         0          1          0          0          1   
1  1  ...         0         0          0          0          1          1   
2  1  ...         1         0          0          0          1          0   
3  1  ...         0         0          1          0          0          0   
4  1  ...         0         0          0          1          0          0   

   Dessus-7  Dessous-3  Dessus-3    id  
0         0          0         1  3711  
1         0          0         1  7613  
2         1          0         1  4420  
3         1          0         1  4940  
4         1          1         0  5320  

[5 rows x 21 columns]

In [53]:
feat = df.drop(columns=['parti'],axis=1)
label = df["parti"]

In [54]:
X_train, X_test, y_train, y_test = train_test_split(feat, label, test_size=0.3, shuffle=True)

In [55]:
sgd = linear_model.SGDClassifier(max_iter = 1000, tol=0)
sgd = sgd.fit(X_train, y_train)

In [56]:
prediction = sgd.predict(X_train)

accuracy_train = accuracy_score(y_train, prediction)
accuracy_train

0.7942857142857143

In [57]:
prediction = sgd.predict(X_test)

accuracy_test = accuracy_score(y_test, prediction)
accuracy_test

0.7933333333333333

In [58]:
import math
resultats_exp = pd.DataFrame({"Modèle": [], "Train": [], "Test": [], "Delta": []})

def add_score(nom, acc_train, acc_test):
    resultats_exp.loc[len(resultats_exp)] = [nom, acc_train, acc_test, math.fabs(acc_train-acc_test)]
    return resultats_exp

add_score("Linéaire", accuracy_train, accuracy_test)

Modèle     Train      Test     Delta
0  Linéaire  0.794286  0.793333  0.000952

# Création d'arbre de décision

In [59]:
clf = RandomForestClassifier(max_depth=6, n_estimators=100)
clf = clf.fit(X_train, y_train)

In [60]:
prediction = clf.predict(X_train)

accuracy_train = accuracy_score(y_train, prediction)
accuracy_train

0.8485714285714285

In [61]:
prediction = clf.predict(X_test)

accuracy_test = accuracy_score(y_test, prediction)
accuracy_test

0.7933333333333333

In [62]:
scores = cross_val_score(clf, feat, label, cv=5, scoring='f1_macro')
scores                                              

C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


array([0.42937853, 0.44198895, 0.44444444, 0.44382022, 0.44067797])

In [63]:
scores = []
best_svr = SVR(kernel='rbf')
kf = KFold(n_splits=3, random_state=None, shuffle=False)
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)


[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [64]:
def get_scores(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [65]:
scores = []
folds = StratifiedKFold(n_splits=3)
kf = KFold(n_splits=3, random_state=None, shuffle=False)
for train_index, test_index in kf.split(feat):
    X_train, X_test, y_train, y_test = feat[train_index], feat[test_index], label[train_index], label[test_index]
    print(get_scores(clf, X_train, X_test, y_train, y_test))

KeyError: "None of [Int64Index([167, 168, 169, 170, 171, 172, 173, 174, 175, 176,\n            ...\n            490, 491, 492, 493, 494, 495, 496, 497, 498, 499],\n           dtype='int64', length=333)] are in the [columns]"

In [66]:
print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, prediction))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test, prediction))
print('\n')
print("=== All AUC Scores ===")
print(clf_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Random Forest: ", clf_cv_score.mean())

=== Confusion Matrix ===
[[119   0]
 [ 31   0]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.79      1.00      0.88       119
           1       0.00      0.00      0.00        31

   micro avg       0.79      0.79      0.79       150
   macro avg       0.40      0.50      0.44       150
weighted avg       0.63      0.79      0.70       150



=== All AUC Scores ===


C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


NameError: name 'clf_cv_score' is not defined

In [67]:
grid_values = {'n_estimators': [1000]}
grid_clf_acc = GridSearchCV(clf, param_grid=grid_values, scoring='roc_auc', n_jobs=1, cv=10)
grid_clf_acc.fit(X_train, y_train)
y_decisions_fn_scores_acc = grid_clf_acc.predict(X_test)
print("Best parametres:", grid_clf_acc.best_params_)
print("Best score:", grid_clf_acc.best_score_)
print('Test:', y_decisions_fn_scores_acc)

C:\Users\LENOVO\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Best parametres: {'n_estimators': 1000}
Best score: 0.5351492819349961
Test: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0]


In [68]:

print(clf.feature_importances_)

[0.09965858 0.11112766 0.11866753 0.11954559 0.10379099 0.06883192
 0.08181994 0.01237884 0.01272159 0.01845097 0.01045749 0.00882985
 0.02152918 0.01596204 0.01406044 0.01612266 0.0139294  0.01060758
 0.00970672 0.13180102]


In [69]:
probs = clf.predict_proba(X_test)
probs

array([[0.86348703, 0.13651297],
       [0.79568729, 0.20431271],
       [0.80315942, 0.19684058],
       [0.88577815, 0.11422185],
       [0.80843459, 0.19156541],
       [0.67533195, 0.32466805],
       [0.9221294 , 0.0778706 ],
       [0.88598462, 0.11401538],
       [0.83548076, 0.16451924],
       [0.73731198, 0.26268802],
       [0.74807538, 0.25192462],
       [0.81832643, 0.18167357],
       [0.79782146, 0.20217854],
       [0.81353874, 0.18646126],
       [0.73356805, 0.26643195],
       [0.87197399, 0.12802601],
       [0.82248121, 0.17751879],
       [0.76171453, 0.23828547],
       [0.8885423 , 0.1114577 ],
       [0.86380362, 0.13619638],
       [0.84763678, 0.15236322],
       [0.60468518, 0.39531482],
       [0.89436112, 0.10563888],
       [0.80058717, 0.19941283],
       [0.77629699, 0.22370301],
       [0.86183252, 0.13816748],
       [0.8179156 , 0.1820844 ],
       [0.87901276, 0.12098724],
       [0.75798654, 0.24201346],
       [0.83826764, 0.16173236],
       [0.

In [70]:
list=[]
for i in range(len(probs)):
    list.append(probs[i][0])
print(list)

[0.8634870337254283, 0.7956872863552309, 0.8031594194157456, 0.8857781466260655, 0.8084345903011808, 0.6753319510643554, 0.9221293974632812, 0.8859846237658635, 0.8354807560237296, 0.7373119849060982, 0.7480753844795619, 0.8183264317918925, 0.7978214604016841, 0.8135387402369143, 0.7335680538111932, 0.8719739857845851, 0.8224812051202776, 0.7617145295717839, 0.8885423045257226, 0.8638036150883256, 0.8476367822712375, 0.6046851761934923, 0.8943611173136773, 0.8005871694332999, 0.7762969873130899, 0.8618325234949463, 0.817915604184792, 0.8790127648258178, 0.7579865396317964, 0.838267643005638, 0.8135534709874801, 0.7213730792238899, 0.7786518426752158, 0.859370197699059, 0.8264352292527372, 0.8662973128372222, 0.7162095168527661, 0.9180724048119078, 0.7490373276438149, 0.8795703412473271, 0.8154241930352605, 0.8485786813802909, 0.6157030265966352, 0.7494404783520168, 0.7503660902500843, 0.7535069690733981, 0.7934476339961382, 0.8565273479732423, 0.8764284048062139, 0.7579646250247586, 0.

In [71]:
liste=pd.DataFrame(list)

In [72]:
predicts = pd.concat([X_test, liste], axis=1)

In [73]:
predicts.head()

id   age  tauxPart  visiPlat  discussion  noteTalent  noteInst    F  \
0     NaN   NaN       NaN       NaN         NaN         NaN       NaN  NaN   
1  7613.0  18.0      24.0      20.0        25.0        18.0      13.0  0.0   
2     NaN   NaN       NaN       NaN         NaN         NaN       NaN  NaN   
3     NaN   NaN       NaN       NaN         NaN         NaN       NaN  NaN   
4     NaN   NaN       NaN       NaN         NaN         NaN       NaN  NaN   

     M  Licence 3  ...  Master 2  cohorte 5  cohorte 6  cohorte 7  Dessous-7  \
0  NaN        NaN  ...       NaN        NaN        NaN        NaN        NaN   
1  1.0        1.0  ...       0.0        0.0        0.0        1.0        1.0   
2  NaN        NaN  ...       NaN        NaN        NaN        NaN        NaN   
3  NaN        NaN  ...       NaN        NaN        NaN        NaN        NaN   
4  NaN        NaN  ...       NaN        NaN        NaN        NaN        NaN   

   Dessus-7  Dessous-3  Dessus-3      id         0  
0       NaN        NaN       NaN     NaN  0.863487  
1       0.0        0.0       1.0  7613.0  0.795687  
2       NaN        NaN       NaN     NaN  0.803159  
3       NaN        NaN       NaN     NaN  0.885778  
4       NaN        NaN       NaN     NaN  0.808435  

[5 rows x 21 columns]

In [74]:
drop=predicts.dropna()

In [75]:
drop=predicts.dropna()

In [76]:
drop.head()

id   age  tauxPart  visiPlat  discussion  noteTalent  noteInst    F  \
1   7613.0  18.0      24.0      20.0        25.0        18.0      13.0  0.0   
6   5171.0  24.0      37.0      12.0        17.0        14.0       6.0  0.0   
8   4712.0  24.0      16.0      21.0        50.0        19.0       3.0  1.0   
9     91.0  18.0      32.0      80.0        70.0         0.0      16.0  0.0   
10  2374.0  24.0      41.0      88.0        80.0        16.0       1.0  0.0   

      M  Licence 3  ...  Master 2  cohorte 5  cohorte 6  cohorte 7  Dessous-7  \
1   1.0        1.0  ...       0.0        0.0        0.0        1.0        1.0   
6   1.0        1.0  ...       0.0        0.0        1.0        0.0        0.0   
8   0.0        1.0  ...       0.0        0.0        0.0        1.0        1.0   
9   1.0        1.0  ...       0.0        0.0        1.0        0.0        1.0   
10  1.0        0.0  ...       0.0        1.0        0.0        0.0        1.0   

    Dessus-7  Dessous-3  Dessus-3      id         0  
1        0.0        0.0       1.0  7613.0  0.795687  
6        1.0        1.0       0.0  5171.0  0.922129  
8        0.0        0.0       1.0  4712.0  0.835481  
9        0.0        1.0       0.0    91.0  0.737312  
10       0.0        1.0       0.0  2374.0  0.748075  

[5 rows x 21 columns]

In [77]:
predicts = predicts.rename(columns={0: 'predictions'})

In [78]:
predicts.head()

id   age  tauxPart  visiPlat  discussion  noteTalent  noteInst    F  \
0     NaN   NaN       NaN       NaN         NaN         NaN       NaN  NaN   
1  7613.0  18.0      24.0      20.0        25.0        18.0      13.0  0.0   
2     NaN   NaN       NaN       NaN         NaN         NaN       NaN  NaN   
3     NaN   NaN       NaN       NaN         NaN         NaN       NaN  NaN   
4     NaN   NaN       NaN       NaN         NaN         NaN       NaN  NaN   

     M  Licence 3  ...  Master 2  cohorte 5  cohorte 6  cohorte 7  Dessous-7  \
0  NaN        NaN  ...       NaN        NaN        NaN        NaN        NaN   
1  1.0        1.0  ...       0.0        0.0        0.0        1.0        1.0   
2  NaN        NaN  ...       NaN        NaN        NaN        NaN        NaN   
3  NaN        NaN  ...       NaN        NaN        NaN        NaN        NaN   
4  NaN        NaN  ...       NaN        NaN        NaN        NaN        NaN   

   Dessus-7  Dessous-3  Dessus-3      id  predictions  
0       NaN        NaN       NaN     NaN     0.863487  
1       0.0        0.0       1.0  7613.0     0.795687  
2       NaN        NaN       NaN     NaN     0.803159  
3       NaN        NaN       NaN     NaN     0.885778  
4       NaN        NaN       NaN     NaN     0.808435  

[5 rows x 21 columns]

In [79]:
resul = drop[['id','predictions']]

KeyError: "['predictions'] not in index"

In [80]:
resul

NameError: name 'resul' is not defined

In [81]:
id=resul['id']
id=pd.DataFrame(id)

NameError: name 'resul' is not defined

In [82]:
 df.loc[df['id']==id]

TypeError: '<' not supported between instances of 'str' and 'int'

In [83]:
add_score("Arbre", accuracy_train, accuracy_test)

Modèle     Train      Test     Delta
0  Linéaire  0.794286  0.793333  0.000952
1     Arbre  0.848571  0.793333  0.055238

# Naive Bayes Classifier

In [84]:
nby = GaussianNB().fit(X_train, y_train)

In [85]:
prediction = nby.predict(X_train)

accuracy_train = accuracy_score(y_train, prediction)
accuracy_train

0.7942857142857143

In [86]:
prediction = nby.predict(X_test)

accuracy_test = accuracy_score(y_test, prediction)
accuracy_test

0.7866666666666666

In [87]:
add_score("Naive Bayes", accuracy_train, accuracy_test)

Modèle     Train      Test     Delta
0     Linéaire  0.794286  0.793333  0.000952
1        Arbre  0.848571  0.793333  0.055238
2  Naive Bayes  0.794286  0.786667  0.007619

# Gradient Boosting Classifier

In [88]:
gbc = GradientBoostingClassifier(learning_rate=0.01, max_depth=2, random_state=0)
gbc = gbc.fit(X_train, y_train)

In [89]:
prediction = gbc.predict(X_train)

accuracy_train = accuracy_score(y_train, prediction)
accuracy_train

0.7971428571428572

In [90]:
prediction = gbc.predict(X_test)

accuracy_test = accuracy_score(y_test, prediction)
accuracy_test

0.7933333333333333

In [91]:
add_score("Gradient Boosting", accuracy_train, accuracy_test)

Modèle     Train      Test     Delta
0           Linéaire  0.794286  0.793333  0.000952
1              Arbre  0.848571  0.793333  0.055238
2        Naive Bayes  0.794286  0.786667  0.007619
3  Gradient Boosting  0.797143  0.793333  0.003810

# XGBOOSTER

In [92]:
#DataFlair - Train the model
model=XGBClassifier()
model.fit(X_train, y_train)

ValueError: feature_names must be unique