# Les Tableaux avec Numpy

In [1]:
import numpy as np

In [4]:
#Tableau à une dimension
vector = np.array([12, 4, 7, 9])

In [3]:
vector

array([12,  4,  7,  9])

In [5]:
print(vector)

[12  4  7  9]


In [6]:
# Création d'une matrice
matrice = np.array([[5, 10, 15], [20, 25, 30]])

In [7]:
matrice

array([[ 5, 10, 15],
       [20, 25, 30]])

In [10]:
# Nous souhaitons afficher la deuxième colonne de la deuxième ligne
matrice[1][2]

30

In [11]:
matrice[:1]

array([[ 5, 10, 15]])

In [16]:
#On met en place une matrice
matrix = np.array([[1,2, 3],
                   [10, 11, 12],
                   [20, 21, 22]])
print(matrix)

[[ 1  2  3]
 [10 11 12]
 [20 21 22]]


In [13]:
print(type(matrix))

<class 'numpy.ndarray'>


In [14]:
matrix[0]

array([1, 2, 3])

In [17]:
#Pemière ligne deuxième colonne
matrix[0][1]

2

In [27]:
#Acceder à la première ligne et la deuxième colonne
matrice = np.array([[5, 10, 15], 
                    [20, 25, 30], 
                    [35, 40, 45]])

In [28]:
extraction = matrice[0]

In [29]:
extraction[1]

10

# Taille d'un tableau

In [30]:
print(matrice.shape)

(3, 3)


In [31]:
len(matrice)

3

In [46]:
world_alcohol = np.genfromtxt("D:/world-alcohol.csv", delimiter=",", dtype="U75")

In [48]:
print(type(world_alcohol))

<class 'numpy.ndarray'>


In [47]:
print(world_alcohol)

[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['1986' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['1986' 'Africa' 'Swaziland' 'Other' '5.15']]


In [49]:
world_alcohol[2][4]

'0.5'

In [54]:
first = world_alcohol[1:11]

In [55]:
first

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ['1986', 'Americas', 'Colombia', 'Beer', '4.27'],
       ['1987', 'Americas', 'Saint Kitts and Nevis', 'Beer', '1.98'],
       ['1987', 'Americas', 'Guatemala', 'Other', '0'],
       ['1987', 'Africa', 'Mauritius', 'Wine', '0.13'],
       ['1985', 'Africa', 'Angola', 'Spirits', '0.39'],
       ['1986', 'Americas', 'Antigua and Barbuda', 'Spirits', '1.55'],
       ['1984', 'Africa', 'Nigeria', 'Other', '6.1']], dtype='<U75')

In [56]:
twenty = world_alcohol[1:21, 1:3]

In [57]:
twenty

array([['Western Pacific', 'Viet Nam'],
       ['Americas', 'Uruguay'],
       ['Africa', "Cte d'Ivoire"],
       ['Americas', 'Colombia'],
       ['Americas', 'Saint Kitts and Nevis'],
       ['Americas', 'Guatemala'],
       ['Africa', 'Mauritius'],
       ['Africa', 'Angola'],
       ['Americas', 'Antigua and Barbuda'],
       ['Africa', 'Nigeria'],
       ['Africa', 'Botswana'],
       ['Americas', 'Guatemala'],
       ['Western Pacific', "Lao People's Democratic Republic"],
       ['Eastern Mediterranean', 'Afghanistan'],
       ['Western Pacific', 'Viet Nam'],
       ['Africa', 'Guinea-Bissau'],
       ['Americas', 'Costa Rica'],
       ['Africa', 'Seychelles'],
       ['Europe', 'Norway'],
       ['Africa', 'Kenya']], dtype='<U75')

In [59]:
print(world_alcohol)

[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['1986' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['1986' 'Africa' 'Swaziland' 'Other' '5.15']]
